/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classe;

/**
 *
 * @author João P. Arquim
 */
public class TelaSuperCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaSuperCalculadora
     */
    public TelaSuperCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblInformar = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        lblDivisaoDois = new javax.swing.JLabel();
        lblElevado = new javax.swing.JLabel();
        lblRaizQuad = new javax.swing.JLabel();
        lblRaizCubica = new javax.swing.JLabel();
        lblValorAbsoluto = new javax.swing.JLabel();
        lblResultDiv = new javax.swing.JLabel();
        lblResultEle = new javax.swing.JLabel();
        lblResultRaizQ = new javax.swing.JLabel();
        lblResultRaizC = new javax.swing.JLabel();
        lblResultValorAb = new javax.swing.JLabel();
        spnValor = new javax.swing.JSpinner();
        lblImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setText("Super Calculadora");

        lblInformar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInformar.setText("Informe um valor:");

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculator-icon_34473.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblDivisaoDois.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDivisaoDois.setText("Resto da divisão por 2:");

        lblElevado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblElevado.setText("Elevado ao cubo:");

        lblRaizQuad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblRaizQuad.setText("Raiz Quadrada:");

        lblRaizCubica.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblRaizCubica.setText("Raiz Cúbica:");

        lblValorAbsoluto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblValorAbsoluto.setText("Valor Absoluto:");

        lblResultDiv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblResultDiv.setForeground(new java.awt.Color(0, 0, 204));
        lblResultDiv.setText("0");

        lblResultEle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblResultEle.setForeground(new java.awt.Color(0, 0, 204));
        lblResultEle.setText("0");

        lblResultRaizQ.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblResultRaizQ.setForeground(new java.awt.Color(0, 0, 204));
        lblResultRaizQ.setText("0");

        lblResultRaizC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblResultRaizC.setForeground(new java.awt.Color(0, 0, 204));
        lblResultRaizC.setText("0");

        lblResultValorAb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblResultValorAb.setForeground(new java.awt.Color(0, 0, 204));
        lblResultValorAb.setText("0");

        spnValor.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/meter_calculatoralt_11441.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDivisaoDois)
                                .addGap(66, 66, 66))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRaizQuad)
                                    .addComponent(lblElevado)
                                    .addComponent(lblRaizCubica)
                                    .addComponent(lblValorAbsoluto))
                                .addGap(38, 38, 38)))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblInformar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnCalcular)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResultDiv, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblResultEle, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblResultRaizQ, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblResultRaizC, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblResultValorAb, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(116, 116, 116)
                        .addComponent(lblImagem)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInformar)
                    .addComponent(btnCalcular)
                    .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDivisaoDois)
                            .addComponent(lblResultDiv))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResultEle)
                            .addComponent(lblElevado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblResultRaizQ)
                            .addComponent(lblRaizQuad))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRaizCubica)
                            .addComponent(lblResultRaizC))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorAbsoluto)
                            .addComponent(lblResultValorAb)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblImagem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        int valor = Integer.parseInt(spnValor.getValue().toString());
        //resto da divisão por dois
        int resto = valor % 2;
        //elevando o valor ao cubo
        double elevado = Math.pow(valor, 3);
        //calculando a raiz cubica do valor
        double cubo = Math.cbrt(valor);
        //calculando a raiz quadrada do valor
        double raizquad = Math.sqrt(valor);
        //valor absoluto do numero
        int abs = Math.abs(valor);
        
        //setando os valores para os seus labels especificos
        lblResultDiv.setText(Integer.toString(resto));
        //usando o String.format para organizar os numeros decimais
        lblResultEle.setText(String.format("%.2f", elevado));
        lblResultRaizC.setText(String.format("%.2f", cubo));
        lblResultRaizQ.setText(String.format("%.2f",raizquad));
        lblResultValorAb.setText(Integer.toString(abs));
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSuperCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lblDivisaoDois;
    private javax.swing.JLabel lblElevado;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblInformar;
    private javax.swing.JLabel lblRaizCubica;
    private javax.swing.JLabel lblRaizQuad;
    private javax.swing.JLabel lblResultDiv;
    private javax.swing.JLabel lblResultEle;
    private javax.swing.JLabel lblResultRaizC;
    private javax.swing.JLabel lblResultRaizQ;
    private javax.swing.JLabel lblResultValorAb;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorAbsoluto;
    private javax.swing.JSpinner spnValor;
    // End of variables declaration//GEN-END:variables
}
